version: "3"

services:
    nginx:
        build: .
        restart: unless-stopped
        ports:
            - 5000:5000
        # volumes:
        #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - userservice
            - statusservice
            - storyservice

    userservice:
        build: ./DS Step-2/user
        image: mahtabhj/userservice
        restart: unless-stopped
        depends_on:
            - userdb

    userdb:
        image: mongo:latest

      

        restart: unless-stopped
        volumes:
            - /mongo:/data/db

    statusservice:
        build: ./DS Step-2/status
        image: mahtabhj/statusservice
        restart: unless-stopped
        depends_on:
            - statusdb

    statusdb:
        image: mongo:latest

        

        restart: unless-stopped

    storyservice:
        build: ./DS Step-2/story
        image: mahtabhj/storyservice
        restart: unless-stopped
        depends_on:
            - storydb
            - storyobjectdb

    storydb:
        image: mongo:latest

        

        restart: unless-stopped

    storyobjectdb:
        image: minio/minio:latest
        environment:
            - MINIO_ACCESS_KEY=ILdloFV62IoAlMOV
            - MINIO_SECRET_KEY=bKSQ8DzAZO1wsP5Q9kikl8IBHMAXigZz
            
        command: server --address 0.0.0.0:9000 /data
